config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :categorizations

      resources :categories

      resources :reviews

      resources :places

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "places#index"
  resources :categorizations
  resources :categories
  resources :reviews
  resources :places
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
require "open-uri"
class Place < ApplicationRecord
  before_validation :geocode_location

  def geocode_location
    if location.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(location)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.location_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.location_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.location_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  mount_base64_uploader :image, ImageUploader

  # Direct associations

  has_many   :categorizations,
             dependent: :destroy

  has_many   :reviews,
             dependent: :destroy

  # Indirect associations

  has_many   :reviewers,
             through: :reviews,
             source: :reviewer

  has_many   :categories,
             through: :categorizations,
             source: :category

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/places_controller.rb
class Api::V1::PlacesController < Api::V1::GraphitiController
  def index
    places = PlaceResource.all(params)
    respond_with(places)
  end

  def show
    place = PlaceResource.find(params)
    respond_with(place)
  end

  def create
    place = PlaceResource.build(params)

    if place.save
      render jsonapi: place, status: :created
    else
      render jsonapi_errors: place
    end
  end

  def update
    place = PlaceResource.find(params)

    if place.update_attributes
      render jsonapi: place
    else
      render jsonapi_errors: place
    end
  end

  def destroy
    place = PlaceResource.find(params)

    if place.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: place
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[show edit update destroy]

  def index
    @q = Place.ransack(params[:q])
    @places = @q.result(distinct: true).includes(:reviews, :categorizations,
                                                 :categories, :reviewers).page(params[:page]).per(10).order(:name)
    @location_hash = Gmaps4rails.build_markers(@places.where.not(location_latitude: nil)) do |place, marker|
      marker.lat place.location_latitude
      marker.lng place.location_longitude
    end
  end

  def show
    @categorization = Categorization.new
    @review = Review.new
  end

  def new
    @place = Place.new
  end

  def edit; end

  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to @place, notice: "Place was successfully created."
    else
      render :new
    end
  end

  def update
    if @place.update(place_params)
      redirect_to @place, notice: "Place was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @place.destroy
    redirect_to places_url, notice: "Place was successfully destroyed."
  end

  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :description, :image, :location)
  end
end

app/views/places/_all_photos_map.html.erb
<div id="location_map" style="height: 480px;"></div>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers(<%= raw @location_hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/places/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4 d-flex justify-content-between">
    <span><%= place.name %></span>

    <span><%= place.reviews.average(:rating) %>★</span>
  </h2>
  <div class="card-body">
    <p class="lead">
      <% @place.categories.order(:name).each do |category| %>
        <a href="/categories/<%= category.id %>" class="btn btn-secondary">
          <%= category %>
        </a>
      <% end %>
    </p>

    <p class="lead">
      <%= place.description %>
    </p>

    <% if place.image.present? %>
      <%= cl_image_tag @place.image, class: "img-fluid" %>
    <% end %>

    <div>
      <%= render partial: "places/one_photo_map" %>
    </div>

    
    <% if current_user.admin? %>
      <div class="row mt-3">
        <div class="col">
          <%= link_to_show_or_back place, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
        </div>

        <div class="col">
          <%= link_to edit_place_url(place), class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </div>

        <div class="col">
          <%= link_to place, method: :delete, data: { confirm: "Do you really want to delete this place?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/places/_form.html.erb
<% was_validated = place.errors.any? %>

<%= form_with(model: place, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = place.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% place.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = place.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% place.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = place.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% place.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% location_class = "form-control" %>
    <% location_was_invalid = place.errors.include?(:location) %>

    <% if was_validated %>
      <% if location_was_invalid %>
        <% location_class << " is-invalid" %>
      <% else %>
        <% location_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :location %>
    <%= f.text_field :location, class: location_class, placeholder: "Enter location" %>
    <% if location_was_invalid %>
      <% place.errors.full_messages_for(:location).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/places/_list_item.html.erb
<%= link_to place, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= place %>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/places/_place_categories.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Categories
  </div>

  <ul class="list-group list-group-flush">
    <% @place.categories.each do |category| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/categories/<%= category.id %>">
          <%= category %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/places/_place_categorizations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Categories

    <a data-toggle="collapse" href="#place_categorizations_new_form">
      Add category
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @place.categorizations.joins(:category).merge(Category.order(:name)).each do |categorization| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to categorization.category, categorization.category.name %>

        <%= link_to categorization, method: :delete, data: { confirm: "Do you really want to delete this categorization" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="place_categorizations_new_form">
        <%= render partial: "places/place_categorizations_new_form" %>
      </div>
    </div>
  </ul>
</div>

app/views/places/_place_categorizations_new_form.html.erb
<%= form_with(model: @categorization, local: true) do |f| %>

  <%= f.hidden_field :place_id, value: @place.id %>

  <div class="form-group">
    <%= f.label :category_id %>

    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Add category to place", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/places/_place_reviewers.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Reviewers
  </div>

  <ul class="list-group list-group-flush">
    <% @place.reviewers.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/places/_place_reviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Reviews

    <a data-toggle="collapse" href="#place_reviews_new_form">
      Add review
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @place.reviews.each do |review| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-body">
            <h5 class="mt-0 d-flex justify-content-between">
              <span><%= review.reviewer.to_s %></span>

              <span>
                <%= "★" * review.rating %>
              <span>
            </h5>
            <p class="lead"><%= simple_format review.body %></p>
          </div>
        </div>
        

        <% if current_user == review.reviewer %>
          <%= link_to review, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="place_reviews_new_form">
        <%= render partial: "places/place_reviews_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/places/_place_reviews_new_form.html.erb
<%= form_with(model: @review, local: true) do |f| %>

  <%= f.hidden_field :place_id, value: @place.id %>

  <%= f.hidden_field :reviewer_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.select :rating, (1..5).to_a, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>

    <%= f.text_area :body, class: "form-control" %>
  </div>


  <%= f.submit "Create review", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/places/_places_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "places_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :categories_id_eq_any, "Categories" %>
    <div>
    <% Category.all.each do |category| %>
      <label>
        <%= check_box_tag('q[categories_id_eq_any][]', category.id, (true if @q.categories_id_eq_any.try(:include?, category.id))) %>
        <%= category.name %>
      </label>
    <% end %>
    </div>
  </div>

  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/places" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#places_filters">
  Show filters
</a>

app/views/places/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Place #<%= @place.id %>
      </h2>

      <div class="card-body">
        <%= render "form", place: @place %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Places

      <%= link_to new_place_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "places/places_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "places/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Places

        <%= link_to new_place_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @places, partial: "list_item", as: :place %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @places, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @place, partial: "card", as: :place %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "places/place_reviews" %>
  </div>
</div>

<% if current_user.admin? %>
  <div class="row justify-content-center mb-3">
    <div class="col-md-8">
      <%= render partial: "places/place_categorizations" %>
    </div>
  </div>
<% end %>